server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/MobilizUser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
jwt:
  secretKey: aaa #${java6secretkey}
  audience: aaa #${java6audience}
  issuer: aaa #${java6issuer}
rabbitmq:
  userQueue: bbb

swagger:
  ui:
    path: /swagger-ui.html  # Swagger UI'nin URL'si
    api-docs:
      path: /v3/api-docs    # API dökümantasyonunun URL'si