server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/MobilizVehicle
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: vehicle-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
jwt:
  secretKey: aaa #${javasecretkey}
  audience: aaa #${javaaudience}
  issuer: aaa #${javaissuer}

rabbitmq:
  vehicleQueue: aaa